### ISSUE TITLE
Corners not rounded

### ISSUE THREAD

**Issue by DoctorJellyface** [KoKuToru/gTox#103]
GNOME 3.16. Not sure if you see it too. If not, I'll send you a screenshot, but tomorrow, becasue I'm really tired.

**Comment by KoKuToru** [comment]
Yeah the top-left when only the Contact List is visible.
I am sure I fixed this once, no idea why it's here again..

**Comment by DoctorJellyface** [comment]
Hm, and they don't seem to have shadows. Also, I think it happened in the profile overview.
