### ISSUE TITLE
Can't see message text

### ISSUE THREAD

**Issue by DoctorJellyface** [KoKuToru/gTox#104]
I do see that a message came, and it has an entry, but the area where the text should be is like non-existent. I can't read anything.

**Comment by KoKuToru** [comment]
Probably a old client sending a message to the new client..
When a old client sends a message it will come as 0-length message on the new client.

I should catch this and display a error message !

**Comment by KoKuToru** [comment]
Shouldn't be any problem anymore, all main clients support new api now (includes qtox)
https://blog.tox.im/2015/04/27/new-api-gsoc-2015
