### ISSUE TITLE
  // , Listing on tox.im

### ISSUE THREAD

**Issue by v6** [KoKuToru/gTox#128]
// , 

This looks like a great replacement for [Venom][ϕ], which has quietly [vaporized][effort]. 

I think it's silly that μTox wants to be the Tox client of choice for every single platform. 

A client specific to a platform, like gTox, seems like a good way to go. 

How can I add gTox to [wiki.tox.im/Binaries][advertisement]? 

[ϕ]: https://github.com/naxuroqa/Venom/issues/284
[effort]: https://youtu.be/-DT7bX-B1Mg?t=27s
[advertisement]: https://wiki.tox.im/Binaries

**Comment by DoctorJellyface** [comment]
It's not ready yet.

**Comment by d9h02f** [comment]
Neither are any of the other Tox clients, or even Tox core itself.

**Comment by v6** [comment]
// , The folks who are currently using Tox, right now, will file bug reports and may be able to help, too.

**Comment by Spagy** [comment]
This can probably be closed. gTox is listed here https://wiki.tox.chat/users/clients

**Comment by KoKuToru** [comment]
Yeah it's listed now, binary is an other topic
