### ISSUE TITLE
New profile unusable before restarting gTox

### ISSUE THREAD

**Issue by Spagy** [KoKuToru/gTox#137]
![screenshot](https://cloud.githubusercontent.com/assets/5479401/8610879/1b0212d6-26b0-11e5-9327-b48ccc0bc292.png)
When a new profile is added, it is greyed out until gTox has been restarted. See New Smith gTox shouldn't need to be restarted for you to be able to use a new profile.

**Comment by KoKuToru** [comment]
It's because of #131 and will be fixed when if merge #134
