### ISSUE TITLE
Implement a way of changing profile without restart

### ISSUE THREAD

**Issue by Spagy** [KoKuToru/gTox#138]
It would be nice to be able to change profiles without restarting gTox

**Comment by KoKuToru** [comment]
You can have multiple instances, just start gTox, while the old one runs.
In Gnome you need to right click on gTox and tell it to open a new one.
It won't create a new process, it will just popup the profile selection on the current running gTox process.

I didn't plan to add a "Open profile selection" or "Switch profile" button or menu entry.
But I will think about it

Maybe in the status-menu below "Exit" a "Change profile" ?
