### ISSUE TITLE
Make toxmm2::profile cross platform

### ISSUE THREAD

**Issue by KoKuToru** [KoKuToru/gTox#144]
In `toxmm-rewrite`-branch.

Update `src/tox/profile.cpp` to be cross platform compatible,
right now it uses `open` and `flock`.

Use `Gio::File`, research if `Gio::File` can lock files...
Atomic-overwrite can be done with `Gio::File::replace`

**Comment by Spagy** [comment]
Is file locking for stopping other instances of gTox from opening a profile or to stop other programs?

**Comment by KoKuToru** [comment]
The main idea was to stop gtox instances and other clients from opening a profile thats currently running. It's not part of the STS but I think it should.. 

It's only blocking write, it's possible to read when locked
