### ISSUE TITLE
Empty state ?

### ISSUE THREAD

**Issue by eternal-sorrow** [KoKuToru/gTox#147]
When I start gtox, it crashes with following error message:

```
(gTox:5399): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: Empty state ?

Trace/breakpoint trap
```

**Comment by KoKuToru** [comment]
It sure could have a better error message..
The profile you try to load is 0Bytes big.. 

You get this directly after stating gTox ? Or after you selected a profile ?
Do you have any profiles ?

**Comment by eternal-sorrow** [comment]
>You get this directly after stating gTox ?
yes
>Do you have any profiles ?
may ones be there after using another client? I'm starting gtox firsttime on my computer.

**Comment by eternal-sorrow** [comment]
just checked: there is empty file ~/.config/tox/tox_save.tox

I've deleted it, then tried to run gtox, but got the same. Empty file appeared there again.

**Comment by eternal-sorrow** [comment]
OK, renaming the directory ~/.config/tox solved this issue, but I lost my old profile. Not very big loss though.

**Comment by KoKuToru** [comment]
How did you install gTox ? I commited a fix (I hope).

**Comment by eternal-sorrow** [comment]
Via gentoo-overlay-tox.

**Comment by KoKuToru** [comment]
I see then a simple reinstall/build will do the trick to get the newest version (because it uses git master)

**Comment by eternal-sorrow** [comment]
OK, now this empty file is shown as "Profile cannot be loaded for an unknown reason". I think, this may be closed.
