### ISSUE TITLE
Failing to build (possibly user error)

### ISSUE THREAD

**Issue by Algram** [KoKuToru/gTox#179]
I am trying to build gTox but I get this error:
```
gTox/src/tox/types.cpp:27:23: schwerwiegender Fehler: uuid/uuid.h: Datei oder Verzeichnis nicht gefunden
Kompilierung beendet.
```

**Comment by KoKuToru** [comment]
You need `libuuid`, looks like it's missing in the dependencies..

**Comment by Algram** [comment]
Yeah, I had to install the package "libuuid-devel" on Fedora. Now it is workign fine, thanks :)
