### ISSUE TITLE
Starting gTox crashes entire network

### ISSUE THREAD

**Issue by Algram** [KoKuToru/gTox#180]
After successfuly building, I started gTox. After that my whole network crashed. Not only on my computer but for every device connected to my router. I can reproduce the Problem 100% of all times and only restarting the router fixes it.

I have never seen something like that caused by a single program but I am certain it is the cause.

**Comment by KoKuToru** [comment]
how would a software crash your network .. Anyways whatever network related problemens you have are hardly gtoxs fault.

gtox does not connect in anyway with any network (or internet).
Every network related is done by toxcore.

What toxcore version are you using ?
Do other clients work ?

**Comment by iphydf** [comment]
Does this happen if you disable UDP?

**Comment by Algram** [comment]
If I disable UDP it doesnt block the network and gTox starts working. Do you know what the error is?

**Comment by KoKuToru** [comment]
How did you disable udp ?

**Comment by Algram** [comment]
I've red somewhere that using lsof can do the trick for blocking udp packages.

`sudo lsof -i UDP`

**Comment by KoKuToru** [comment]
is that so ? well if it works..

Anyways I am working on an update for gtox. 
Which will make the UDP-option in the gtox-settings working.

**Comment by Algram** [comment]
Hm so you are pretty sure it is a problem with toxcore? Because qTox is working for me. (*Q*-Tox, not G-Tox)

**Comment by KoKuToru** [comment]
maybe qtox defaults to udp-disabled ? no idea.. (even though my qtox here says udp enabled)
but yeah it's toxcore fault and/or your routers fault.

**Comment by Algram** [comment]
Okey, I guess I'll wait until the update to disable UDP. Thank you for your help!

**Comment by iphydf** [comment]
It can be various things. Your router might not like broadcasts (unlikely), or NAT hole punching might trigger a bug in your router. I consider hole punching most likely to be the reason, and it's not something tox can really fix. The reason I think this is most likely is that few other applications do it.
