### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by KoKuToru** [KoKuToru/gTox#63]
Use keywords for translation ?
Will german fallback to english when german misses the translation ?

Needs to be checked.

I think we should do this for the first release.

**Comment by KoKuToru** [comment]
Fallsback now, but translation for v0.1 not finish yet

**Comment by KoKuToru** [comment]
Keywords should be replaced with normal text.. 

whoever has time for this, feel free to do it

**Comment by solbjorn** [comment]
I can help you with translating ```ru.po``` to russian, if you wish.

**Comment by KoKuToru** [comment]
@solbjorn feel free to update it

If you have experiences with translating, I would love to hear your opinion on this whole gettext thing.. 

I feel like it's very ugly.. here

**Comment by KoKuToru** [comment]
translation itself is more or less finish, the use of gettext is questionable.. will make separated issues for gettext
