### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by DoctorJellyface** [KoKuToru/gTox#83]
I know two months shouldn't be considered dead, but still. Is this dead? I got my hopes up when I saw this project after I found out that Venom was dead.

**Comment by KoKuToru** [comment]
Nah is not death, I am just working more than usual right now, so less time for private projects.
But next week I will have a full free week.
I am hoping to finish everything for the v0.1 Milestone (first release).
Then receive files / voice / video chat..

**Comment by DoctorJellyface** [comment]
Great! \*mops cold sweat from forehead\*
