### ISSUE TITLE
New Network Protocol

### ISSUE THREAD

**Issue by KoKuToru** [KoKuToru/gTox#91]
I had some confusing problems while testing the new apiupdate-branch...
and found the following issue https://github.com/irungentoo/toxcore/issues/1307

Not really a problem, we just need to make sure to use the same "version" while testing.

For our first release, I think we should wait until uTox, qTox, Toxic, ... releases binaries with the new toxcore..

For the gtox-git ArchLinux package.. we probably will need a way to inform users that it will use the newest toxcore and won't be compatible with older clients.
Dialog when starting gTox ? With a "don't show again" option ?

**Comment by MauriceMohlek** [comment]
No message, since Tox isn't stable.

**Comment by KoKuToru** [comment]
reopen, because it is still a problem

**Comment by DoctorJellyface** [comment]
Just echo something in the .install file.
