### ISSUE TITLE
Implement Tox-STS

### ISSUE THREAD

**Issue by KoKuToru** [KoKuToru/gTox#92]
https://github.com/Tox/Tox-STS/blob/master/STS.md
https://github.com/irungentoo/Tox_Client_Guidelines

I think it would be a good idea..

- [x] The Tox ID
- [X] [Friend Requests](https://github.com/Tox/Tox-STS/blob/master/STS.md#user-identification--interaction) (because it's not possible yet.. without alias, and message is required)
- [ ] [Friends List](https://github.com/Tox/Tox-STS/blob/master/STS.md#friends-list)
- [ ] [Group Messaging](https://github.com/Tox/Tox-STS/blob/master/STS.md#group-messaging)
- [ ] #122 [Multimedia messaging](https://github.com/Tox/Tox-STS/blob/master/STS.md#multimedia-messaging)
- [X] [Emoticons](https://github.com/Tox/Tox-STS/blob/master/STS.md#emoticons) (Unicode Emojis are supported, thanks GTK)
- [ ] [Message splitting](https://github.com/Tox/Tox-STS/blob/master/STS.md#message-splitting)
- [X] [Encodings](https://github.com/Tox/Tox-STS/blob/master/STS.md#encodings)
- [x] #97 [Tox data directory](https://github.com/Tox/Tox-STS/blob/master/STS.md#tox-data-directory)
- [x] [Logging](https://github.com/Tox/Tox-STS/blob/master/STS.md#logging) (why it is called Logging ?)
- [ ] [User Profile Encryption](https://github.com/Tox/Tox-STS/blob/master/STS.md#user-profile-encryption)
- [ ] [NoSpam Changing](https://github.com/Tox/Tox-STS/blob/master/STS.md#nospam-changing)
- [ ] [User profiles](https://github.com/Tox/Tox-STS/blob/master/STS.md#user-profiles) (see also Tox data directory, it looks like uTox doesn't call its files '.tox' ...)
- [x] #26 [Profile management](https://github.com/Tox/Tox-STS/blob/master/STS.md#profile-management)
- [ ] [Recommendations regarding profile management](https://github.com/Tox/Tox-STS/blob/master/STS.md#recommendations-regarding-profile-management)
- [ ] #27 [Avatars](https://github.com/Tox/Tox-STS/blob/master/STS.md#avatars)
- [ ] #93 [Tox URI scheme](https://github.com/Tox/Tox-STS/blob/master/STS.md#tox-uri-scheme)
- [ ] [DNS Discovery](https://github.com/Tox/Tox-STS/blob/master/STS.md#dns-discovery)
- [ ] Translation of STS Terminology

We should create a issue for each of these items and reference them..

**Comment by KoKuToru** [comment]
STS is dead ? the most important things are already implemented

**Comment by quininer** [comment]
https://github.com/Tox/Tox-Client-Standard

This seems to be an alternative STS.
and I think it is very important to the group chat.
